---
- name: Instalar Docker y Portainer
  hosts: portainer
  become: true
  tasks:
    - name: Instalar dependencias previas
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - python3-pip # Necesario para el módulo de docker de ansible
        state: latest
        update_cache: yes

    - name: Crear directorio para las llaves apt
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Añadir GPG key oficial de Docker
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
        force: true

    - name: Añadir repositorio de Docker
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian trixie stable \
        $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
        tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Instalar Docker y plugins
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: Asegurar que Docker está corriendo
      service:
        name: docker
        state: started
        enabled: yes

    # 2. PREPARACIÓN PARA ANSIBLE (Librería Python)
    - name: Instalar librería Python para Docker (SDK)
      pip:
        name: docker
        break_system_packages: true # Necesario en versiones modernas de Ubuntu/Debian

    # 3. DESPLIEGUE DE PORTAINER
    - name: Crear volumen para datos de Portainer
      docker_volume:
        name: portainer_data

    - name: Desplegar contenedor Portainer
      docker_container:
        name: portainer
        image: portainer/portainer-ce:latest
        restart_policy: always
        ports:
          - "8000:8000"
          - "9443:9443"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "portainer_data:/data"