# Redirige todo el tráfico HTTP a HTTPS
server {
    listen 80;
    server_name 192.168.200.109;
    return 301 https://$host$request_uri;
}

server {
    listen 50001 ssl;
    server_name 192.168.200.109;

    root /var/www/html/moodle/public;
    index index.php;

    error_log /var/log/nginx/moodle-error.log;
    access_log /var/log/nginx/moodle-access.log;

    ssl_certificate /etc/ssl/moodle/moodle.crt;
    ssl_certificate_key /etc/ssl/moodle/moodle.key;

    location / {
        try_files $uri $uri/ /r.php?$args;
    }

    location ~ \.php(/|$) {
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        set $path_info $fastcgi_path_info;

        try_files $fastcgi_script_name $fastcgi_script_name/ /r.php$is_args$args;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $path_info;
        fastcgi_param PATH_TRANSLATED $document_root$path_info;

        fastcgi_pass unix:/var/run/php/php8.4-fpm.sock;
        fastcgi_index index.php;
        fastcgi_intercept_errors on;
    }

    location ~ /\.(?!well-known).* {
        return 404;
    }

    location ~* \.(jpg|jpeg|png|gif|ico|css|js|svg|woff|woff2|ttf|eot)$ {
        expires 30d;
        add_header Cache-Control "public";
        access_log off;
    }

    client_max_body_size 100M;
}


