# Playbook de despliegue del servicio Web
- name: Web Server
  hosts: webserver
  become: yes
  tasks:

    # Instalamos Apache
    - name: Instalar Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    # Iniciamos Apache
    - name: Iniciar Apache
      service:
        name: apache2
        state: started
        enabled: yes

    # Instalamos el servicio de firewall que en Debian no viene por defecto
    - name: Instalar ufw
      apt:
        name: ufw
        state: present

    # Activamos UFW
    - name: Activar ufw
      ufw:
        state: enabled

    # Permitimos el puerto 22 para que Ansible pueda seguir conectando
    - name: Permitir puerto 22
      ufw:
        rule: allow
        name: OpenSSH

    # Permitimos el puerto 50000 (tu puerto de despliegue)
    - name: Habilitar puerto 50000
      ufw:
        rule: allow
        port: '50000'
        proto: tcp

    # Copiamos el archivo index.html al servidor gestionado
    - name: Copiar archivo index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'